project_id = "mhmwzlzccxjsihqalrau"

[functions.register-partner]
verify_jwt = false

[functions.fetch-crif-report]
verify_jwt = false

[functions.fetch-cibil-report]
verify_jwt = false

[functions.fetch-experian-report]
verify_jwt = false

[functions.fetch-equifax-report]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
